<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCc1wt3x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCc1wt3x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCc1wt3x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCc1wt3x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCc1wt3x\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Cc1wt3x',
    'container.build_id' => '019b2d17',
    'container.build_time' => 1534059924,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCc1wt3x');
