CREATE DATABASE SoftUni;

CREATE TABLE Towns (
	Id INT PRIMARY KEY IDENTITY  NOT NULL,
	[Name] NVARCHAR(100) NOT NULL
)

CREATE TABLE Addresses (
	Id INT PRIMARY KEY IDENTITY  NOT NULL,
	AddressText NVARCHAR(100) NOT NULL,
	TownId INT FOREIGN KEY REFERENCES Towns (Id) NOT NULL
)

CREATE TABLE Departments (
	Id INT PRIMARY KEY IDENTITY  NOT NULL,
	[Name] NVARCHAR(100) NOT NULL
)

CREATE TABLE Employees (
	Id INT PRIMARY KEY IDENTITY  NOT NULL,
	FirstName NVARCHAR(100) NOT NULL,
	MiddleName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	JobTitle NVARCHAR(100) NOT NULL,
	DepartmentId INT FOREIGN KEY REFERENCES Departments (Id) NOT NULL,
	HireDate DATE NOT NULL,
	Salary MONEY NOT NULL,
	AddressId INT FOREIGN KEY REFERENCES Addresses (Id)
)



